# Techniki eksploracji danych wielowymiarowych 20.02

# Cwiczenie 1

In [1]:
import pandas as pd
import numpy as np
import random

# 1

In [2]:
A=[]
i=0
while i<10:
    x=random.randrange(1,20)
    A.append(x)
    i=i+1
wektorA=np.vstack(A)
print(wektorA)

[[ 1]
 [18]
 [ 6]
 [ 3]
 [ 5]
 [ 9]
 [ 2]
 [ 8]
 [ 4]
 [ 6]]


# 2

In [3]:
B=[]
i=0
while i<10:
    x=random.uniform(0,1)
    B.append(x)
    i=i+1
wektorB=np.vstack(B)
print(wektorB)

[[0.72235659]
 [0.75836388]
 [0.70758816]
 [0.92980083]
 [0.40377044]
 [0.4354779 ]
 [0.91856863]
 [0.14835865]
 [0.95876042]
 [0.60797136]]


# 3

In [4]:
wektorC=wektorA*wektorB
print(wektorC)

[[ 0.72235659]
 [13.65054988]
 [ 4.24552897]
 [ 2.7894025 ]
 [ 2.01885222]
 [ 3.91930108]
 [ 1.83713726]
 [ 1.18686918]
 [ 3.83504167]
 [ 3.64782815]]


# 4

In [5]:
c=2
wektor4=wektorA*c
print(wektor4)

[[ 2]
 [36]
 [12]
 [ 6]
 [10]
 [18]
 [ 4]
 [16]
 [ 8]
 [12]]


# 5

In [6]:
W=np.random.randint(100, size=(4,4))
print(W)

[[58 56 84 55]
 [80  4 13 65]
 [29 48 33 55]
 [60 85 30 66]]


# 6

In [7]:
diag=np.diagonal(W)
print(diag)

[58  4 33 66]


# 7

In [8]:
print(f'{W.transpose()}')

[[58 80 29 60]
 [56  4 48 85]
 [84 13 33 30]
 [55 65 55 66]]


# Ćwiczenie 2

# 1

In [9]:
dane=pd.read_csv('nfloffenseweek3.csv')
pd.read_csv('nfloffenseweek3.csv')

rank                   team  games  points_scored  total_yards  \
0      1       Baltimore Ravens      3             99         1141   
1      2          Detroit Lions      3             95         1227   
2      3          Buffalo Bills      3             91         1324   
3      4     Kansas City Chiefs      3             88         1122   
4      5    Philadelphia Eagles      3             86         1341   
5      6       Cleveland Browns      3             85         1136   
6      7   Jacksonville Jaguars      3             84         1127   
7      8         Miami Dolphins      3             83         1066   
8      9        Atlanta Falcons      3             80         1063   
9     10     Cincinnati Bengals      3             64         1016   
10    11      Las Vegas Raiders      3             64         1040   
11    12  Washington Commanders      3             63         1026   
12    13      Arizona Cardinals      3             62         1060   
13    14      Carolina Panthers      3             62          829   
14    15       Los Angeles Rams      3             61          919   
15    16      Minnesota Vikings      3             58         1032   
16    17   Los Angeles Chargers      3             58         1068   
17    18        New York Giants      3             56          995   
18    19    Pittsburgh Steelers      3             54          818   
19    20          New York Jets      3             52         1110   
20    21          Chicago Bears      3             52          795   
21    22   Tampa Bay Buccaneers      3             51          892   
22    23     New Orleans Saints      3             51         1119   
23    24       Tennessee Titans      3             51          907   
24    25   New England Patriots      3             50         1094   
25    26         Houston Texans      3             49          862   
26    27      Green Bay Packers      3             48         1067   
27    28       Seattle Seahawks      3             47          889   
28    29    San Francisco 49ers      3             47          971   
29    30         Dallas Cowboys      3             46          972   
30    31         Denver Broncos      3             43         1044   
31    32     Indianapolis Colts      3             40          994   

    offensive_plays  yards_per_play  turnovers_lost  fumbles_lost  1st_downs  \
0               166             6.9               3             1         55   
1               203             6.0               2             0         63   
2               213             6.2               5             3         77   
3               180             6.2               3             2         68   
4               208             6.4               1             0         73   
5               210             5.4               1             0         74   
6               204             5.5               1             0         70   
7               167             6.4               2             0         60   
8               181             5.9               7             4         67   
9               227             4.5               6             2         71   
10              182             5.7               5             1         62   
11              216             4.8               5             2         67   
12              222             4.8               1             0         69   
13              163             5.1               3             2         45   
14              175             5.3               7             2         58   
15              187             5.5               4             1         69   
16              197             5.4               3             1         55   
17              195             5.1               3             1         59   
18              174             4.7               3             2         49   
19              222             5.0               7             4         63   
20           

# 2

In [10]:
dane['team'].value_counts()['Miami Dolphins']

1

In [11]:
i = dane.index
index = dane["team"] == 'Arizona Cardinals'
result = i[index]
result.tolist()

[12]

# 3

In [12]:
wiersz1=random.randrange(1,32)
wiersz2=random.randrange(1,32)
print(wiersz1,wiersz2)

15 6


In [13]:
dane=dane.drop([wiersz1,wiersz2])
dane

rank                   team  games  points_scored  total_yards  \
0      1       Baltimore Ravens      3             99         1141   
1      2          Detroit Lions      3             95         1227   
2      3          Buffalo Bills      3             91         1324   
3      4     Kansas City Chiefs      3             88         1122   
4      5    Philadelphia Eagles      3             86         1341   
5      6       Cleveland Browns      3             85         1136   
7      8         Miami Dolphins      3             83         1066   
8      9        Atlanta Falcons      3             80         1063   
9     10     Cincinnati Bengals      3             64         1016   
10    11      Las Vegas Raiders      3             64         1040   
11    12  Washington Commanders      3             63         1026   
12    13      Arizona Cardinals      3             62         1060   
13    14      Carolina Panthers      3             62          829   
14    15       Los Angeles Rams      3             61          919   
16    17   Los Angeles Chargers      3             58         1068   
17    18        New York Giants      3             56          995   
18    19    Pittsburgh Steelers      3             54          818   
19    20          New York Jets      3             52         1110   
20    21          Chicago Bears      3             52          795   
21    22   Tampa Bay Buccaneers      3             51          892   
22    23     New Orleans Saints      3             51         1119   
23    24       Tennessee Titans      3             51          907   
24    25   New England Patriots      3             50         1094   
25    26         Houston Texans      3             49          862   
26    27      Green Bay Packers      3             48         1067   
27    28       Seattle Seahawks      3             47          889   
28    29    San Francisco 49ers      3             47          971   
29    30         Dallas Cowboys      3             46          972   
30    31         Denver Broncos      3             43         1044   
31    32     Indianapolis Colts      3             40          994   

    offensive_plays  yards_per_play  turnovers_lost  fumbles_lost  1st_downs  \
0               166             6.9               3             1         55   
1               203             6.0               2             0         63   
2               213             6.2               5             3         77   
3               180             6.2               3             2         68   
4               208             6.4               1             0         73   
5               210             5.4               1             0         74   
7               167             6.4               2             0         60   
8               181             5.9               7             4         67   
9               227             4.5               6             2         71   
10              182             5.7               5             1         62   
11              216             4.8               5             2         67   
12              222             4.8               1             0         69   
13              163             5.1               3             2         45   
14              175             5.3               7             2         58   
16              197             5.4               3             1         55   
17              195             5.1               3             1         59   
18              174             4.7               3             2         49   
19              222             5.0               7             4         63   
20              159             5.0               4             0         43   
21              186             4.8               4             3         50   
22              187             6.0               9             4         55   
23              168             5.4               6             3        

# 4

In [14]:
dane=dane.iloc[:,[2,1,0]+list(range(3,len(dane.columns)))]
dane=dane.iloc[[len(dane)-1]+list(range(1,len(dane)-1))+[0],:]
dane

games                   team  rank  points_scored  total_yards  \
31      3     Indianapolis Colts    32             40          994   
1       3          Detroit Lions     2             95         1227   
2       3          Buffalo Bills     3             91         1324   
3       3     Kansas City Chiefs     4             88         1122   
4       3    Philadelphia Eagles     5             86         1341   
5       3       Cleveland Browns     6             85         1136   
7       3         Miami Dolphins     8             83         1066   
8       3        Atlanta Falcons     9             80         1063   
9       3     Cincinnati Bengals    10             64         1016   
10      3      Las Vegas Raiders    11             64         1040   
11      3  Washington Commanders    12             63         1026   
12      3      Arizona Cardinals    13             62         1060   
13      3      Carolina Panthers    14             62          829   
14      3       Los Angeles Rams    15             61          919   
16      3   Los Angeles Chargers    17             58         1068   
17      3        New York Giants    18             56          995   
18      3    Pittsburgh Steelers    19             54          818   
19      3          New York Jets    20             52         1110   
20      3          Chicago Bears    21             52          795   
21      3   Tampa Bay Buccaneers    22             51          892   
22      3     New Orleans Saints    23             51         1119   
23      3       Tennessee Titans    24             51          907   
24      3   New England Patriots    25             50         1094   
25      3         Houston Texans    26             49          862   
26      3      Green Bay Packers    27             48         1067   
27      3       Seattle Seahawks    28             47          889   
28      3    San Francisco 49ers    29             47          971   
29      3         Dallas Cowboys    30             46          972   
30      3         Denver Broncos    31             43         1044   
0       3       Baltimore Ravens     1             99         1141   

    offensive_plays  yards_per_play  turnovers_lost  fumbles_lost  1st_downs  \
31              207             4.8               6             2         61   
1               203             6.0               2             0         63   
2               213             6.2               5             3         77   
3               180             6.2               3             2         68   
4               208             6.4               1             0         73   
5               210             5.4               1             0         74   
7               167             6.4               2             0         60   
8               181             5.9               7             4         67   
9               227             4.5               6             2         71   
10              182             5.7               5             1         62   
11              216             4.8               5             2         67   
12              222             4.8               1             0         69   
13              163             5.1               3             2         45   
14              175             5.3               7             2         58   
16              197             5.4               3             1         55   
17              195             5.1               3             1         59   
18              174             4.7               3             2         49   
19              222             5.0               7             4         63   
20              159             5.0               4             0         43   
21              186             4.8               4             3         50   
22              187             6.0               9             4         55   
23              168             5.4               6             3        

# 5

In [15]:
dane.to_csv('dane.csv', index=False)
dane.to_excel('dane.xlsx')

# 6

In [16]:
lista_kolumn=(dane.columns)
lista_kolumn

Index(['games', 'team', 'rank', 'points_scored', 'total_yards',
       'offensive_plays', 'yards_per_play', 'turnovers_lost', 'fumbles_lost',
       '1st_downs', 'passes_completed', 'passes_attempted', 'passing_yards',
       'passing_touchdowns', 'passing_interceptions',
       'net_yards_per_pass_attempt', 'passing_1st_downs', 'rushing_attempts',
       'rushing_yards', 'rushing_touchdowns', 'rushing_yards_per_attempt',
       'rushing_1st_downs', 'penalties', 'penalty_yards', '1st_down_penalties',
       'percentage_scoring_drives', 'percentage_turnover_drives',
       'expected_points'],
      dtype='object')

# 7

In [17]:
lista_kolumn[:5]

Index(['games', 'team', 'rank', 'points_scored', 'total_yards'], dtype='object')

In [18]:
lista_kolumn[-7:]

Index(['rushing_1st_downs', 'penalties', 'penalty_yards', '1st_down_penalties',
       'percentage_scoring_drives', 'percentage_turnover_drives',
       'expected_points'],
      dtype='object')

# 8

In [19]:
dane.iloc[6, 3]

83

# 9

In [20]:
kolumna_6=dane['offensive_plays']
kolumna_6

31    207
1     203
2     213
3     180
4     208
5     210
7     167
8     181
9     227
10    182
11    216
12    222
13    163
14    175
16    197
17    195
18    174
19    222
20    159
21    186
22    187
23    168
24    183
25    184
26    188
27    165
28    189
29    184
30    199
0     166
Name: offensive_plays, dtype: int64

In [21]:
dane=dane.drop(columns=['offensive_plays'])

In [22]:
pd.concat([dane, kolumna_6],axis=1)

games                   team  rank  points_scored  total_yards  \
31      3     Indianapolis Colts    32             40          994   
1       3          Detroit Lions     2             95         1227   
2       3          Buffalo Bills     3             91         1324   
3       3     Kansas City Chiefs     4             88         1122   
4       3    Philadelphia Eagles     5             86         1341   
5       3       Cleveland Browns     6             85         1136   
7       3         Miami Dolphins     8             83         1066   
8       3        Atlanta Falcons     9             80         1063   
9       3     Cincinnati Bengals    10             64         1016   
10      3      Las Vegas Raiders    11             64         1040   
11      3  Washington Commanders    12             63         1026   
12      3      Arizona Cardinals    13             62         1060   
13      3      Carolina Panthers    14             62          829   
14      3       Los Angeles Rams    15             61          919   
16      3   Los Angeles Chargers    17             58         1068   
17      3        New York Giants    18             56          995   
18      3    Pittsburgh Steelers    19             54          818   
19      3          New York Jets    20             52         1110   
20      3          Chicago Bears    21             52          795   
21      3   Tampa Bay Buccaneers    22             51          892   
22      3     New Orleans Saints    23             51         1119   
23      3       Tennessee Titans    24             51          907   
24      3   New England Patriots    25             50         1094   
25      3         Houston Texans    26             49          862   
26      3      Green Bay Packers    27             48         1067   
27      3       Seattle Seahawks    28             47          889   
28      3    San Francisco 49ers    29             47          971   
29      3         Dallas Cowboys    30             46          972   
30      3         Denver Broncos    31             43         1044   
0       3       Baltimore Ravens     1             99         1141   

    yards_per_play  turnovers_lost  fumbles_lost  1st_downs  passes_completed  \
31             4.8               6             2         61                75   
1              6.0               2             0         63                66   
2              6.2               5             3         77                94   
3              6.2               3             2         68                74   
4              6.4               1             0         73                66   
5              5.4               1             0         74                61   
7              6.4               2             0         60                72   
8              5.9               7             4         67                50   
9              4.5               6             2         71                80   
10             5.7               5             1         62                74   
11             4.8               5             2         67                82   
12             4.8               1             0         69                92   
13             5.1               3             2         45                42   
14             5.3               7             2         58                74   
16             5.4               3             1         55                84   
17             5.1               3             1         59                59   
18             4.7               3             2         49                62   
19             5.0               7             4         63                92   
20             5.0               4             0         43                23   
21             4.8               4             3         50                67   
22             6.0               9             4         55                73   
23             5.4               6             3   

# 27.02 Ćwiczenia 2

# zadanie 1 (z kartki)

In [23]:
dane=pd.read_csv('nfloffenseweek3.csv')
pd.read_csv('nfloffenseweek3.csv')

rank                   team  games  points_scored  total_yards  \
0      1       Baltimore Ravens      3             99         1141   
1      2          Detroit Lions      3             95         1227   
2      3          Buffalo Bills      3             91         1324   
3      4     Kansas City Chiefs      3             88         1122   
4      5    Philadelphia Eagles      3             86         1341   
5      6       Cleveland Browns      3             85         1136   
6      7   Jacksonville Jaguars      3             84         1127   
7      8         Miami Dolphins      3             83         1066   
8      9        Atlanta Falcons      3             80         1063   
9     10     Cincinnati Bengals      3             64         1016   
10    11      Las Vegas Raiders      3             64         1040   
11    12  Washington Commanders      3             63         1026   
12    13      Arizona Cardinals      3             62         1060   
13    14      Carolina Panthers      3             62          829   
14    15       Los Angeles Rams      3             61          919   
15    16      Minnesota Vikings      3             58         1032   
16    17   Los Angeles Chargers      3             58         1068   
17    18        New York Giants      3             56          995   
18    19    Pittsburgh Steelers      3             54          818   
19    20          New York Jets      3             52         1110   
20    21          Chicago Bears      3             52          795   
21    22   Tampa Bay Buccaneers      3             51          892   
22    23     New Orleans Saints      3             51         1119   
23    24       Tennessee Titans      3             51          907   
24    25   New England Patriots      3             50         1094   
25    26         Houston Texans      3             49          862   
26    27      Green Bay Packers      3             48         1067   
27    28       Seattle Seahawks      3             47          889   
28    29    San Francisco 49ers      3             47          971   
29    30         Dallas Cowboys      3             46          972   
30    31         Denver Broncos      3             43         1044   
31    32     Indianapolis Colts      3             40          994   

    offensive_plays  yards_per_play  turnovers_lost  fumbles_lost  1st_downs  \
0               166             6.9               3             1         55   
1               203             6.0               2             0         63   
2               213             6.2               5             3         77   
3               180             6.2               3             2         68   
4               208             6.4               1             0         73   
5               210             5.4               1             0         74   
6               204             5.5               1             0         70   
7               167             6.4               2             0         60   
8               181             5.9               7             4         67   
9               227             4.5               6             2         71   
10              182             5.7               5             1         62   
11              216             4.8               5             2         67   
12              222             4.8               1             0         69   
13              163             5.1               3             2         45   
14              175             5.3               7             2         58   
15              187             5.5               4             1         69   
16              197             5.4               3             1         55   
17              195             5.1               3             1         59   
18              174             4.7               3             2         49   
19              222             5.0               7             4         63   
20           

In [30]:
import scipy.stats as stats

In [37]:
dane=pd.read_csv('nfloffenseweek3.csv')
dane=dane.drop(columns=['team','rank'])
srednia=dane.mean()
minimum=dane.min()
maximum=dane.max()
rozstep=(dane.max()-dane.min())
sr_rozk=rozstep/2
odchyl_std=np.std(dane)
skosnosc=dane.skew()


games                         0.000000
points_scored                 0.743409
total_yards                   0.294444
offensive_plays               0.244825
yards_per_play                0.546119
turnovers_lost                0.377095
fumbles_lost                  0.170529
1st_downs                     0.069250
passes_completed             -0.698003
passes_attempted             -0.191506
passing_yards                -0.736258
passing_touchdowns            0.834311
passing_interceptions         0.624254
net_yards_per_pass_attempt    0.417963
passing_1st_downs            -0.753629
rushing_attempts              0.579836
rushing_yards                 0.674914
rushing_touchdowns            0.499761
rushing_yards_per_attempt    -0.019443
rushing_1st_downs             0.502611
penalties                     0.396504
penalty_yards                 0.229210
1st_down_penalties            0.053626
percentage_scoring_drives     0.395962
percentage_turnover_drives    0.473593
expected_points          